/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import telasPesquisas.JDlgPesquisaProduto;
import tools.util;

/**
 *
 * @author vivic
 */
public class JDlgProduto extends javax.swing.JDialog {

     MaskFormatter mascaraModeloAno;
    /** Creates new form JDlgProduto */
    public JDlgProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Produto");
        util.habilitar(false, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime,
                jTxt_vcsValorUnitario, jFmt_vcsModeloAno, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar );
    
         try {
            mascaraModeloAno = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmt_vcsModeloAno.setFormatterFactory(new DefaultFormatterFactory(mascaraModeloAno));
    
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtn_vcsExcluir = new javax.swing.JButton();
        jBtn_vcsAlterar = new javax.swing.JButton();
        jBtn_vcsConfirmar = new javax.swing.JButton();
        jBtn_vcsCancelar = new javax.swing.JButton();
        jBtn_vcsPesquisar = new javax.swing.JButton();
        jBtn_vcsIncluir = new javax.swing.JButton();
        jTxt_vcsNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxt_vcsNome = new javax.swing.JTextField();
        jTxt_vcsTime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxt_vcsCor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxt_vcsTamanho = new javax.swing.JTextField();
        jTxt_vcsCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFmt_vcsModeloAno = new javax.swing.JFormattedTextField();
        jTxt_vcsValorUnitario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtn_vcsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Captura de tela 2024-03-26 233440.png"))); // NOI18N
        jBtn_vcsExcluir.setText("Excluir");
        jBtn_vcsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsExcluirActionPerformed(evt);
            }
        });

        jBtn_vcsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterarIcon.png"))); // NOI18N
        jBtn_vcsAlterar.setText("Alterar");
        jBtn_vcsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsAlterarActionPerformed(evt);
            }
        });

        jBtn_vcsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confimarIcon.png"))); // NOI18N
        jBtn_vcsConfirmar.setText("Confirmar");
        jBtn_vcsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsConfirmarActionPerformed(evt);
            }
        });

        jBtn_vcsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluirIcon.png"))); // NOI18N
        jBtn_vcsCancelar.setText("Cancelar");
        jBtn_vcsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsCancelarActionPerformed(evt);
            }
        });

        jBtn_vcsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisarIcon.png"))); // NOI18N
        jBtn_vcsPesquisar.setText("Pesquisar");
        jBtn_vcsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsPesquisarActionPerformed(evt);
            }
        });

        jBtn_vcsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluirIcon.png"))); // NOI18N
        jBtn_vcsIncluir.setText("Incluir");
        jBtn_vcsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsIncluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome");

        jLabel1.setText("Time");

        jLabel2.setText("Cor");

        jLabel3.setText("Tamanho");

        jLabel7.setText("Código");

        jLabel4.setText("Modelo/Ano");

        jLabel8.setText("Preço:");

        jLabel5.setText("Numero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtn_vcsIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_vcsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_vcsExcluir))
                    .addComponent(jTxt_vcsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsCor, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxt_vcsTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTxt_vcsNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtn_vcsConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_vcsCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_vcsPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTxt_vcsNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsTime, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jFmt_vcsModeloAno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTxt_vcsValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_vcsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_vcsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_vcsTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmt_vcsModeloAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_vcsCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_vcsIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_vcsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_vcsExcluir)
                            .addComponent(jBtn_vcsConfirmar)
                            .addComponent(jBtn_vcsCancelar)
                            .addComponent(jBtn_vcsPesquisar))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_vcsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsExcluirActionPerformed
        util.habilitar(true, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime,jFmt_vcsModeloAno, jTxt_vcsValorUnitario, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(false, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar );
        util.limparCampos(jFmt_vcsModeloAno, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime,jFmt_vcsModeloAno, jTxt_vcsValorUnitario);
        util.mensagem("Registro excluido com sucesso!!!");
    }//GEN-LAST:event_jBtn_vcsExcluirActionPerformed

    private void jBtn_vcsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsAlterarActionPerformed
        util.habilitar(true, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime,jFmt_vcsModeloAno, jTxt_vcsValorUnitario, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(false, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar );
       
    }//GEN-LAST:event_jBtn_vcsAlterarActionPerformed

    private void jBtn_vcsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsConfirmarActionPerformed
        util.habilitar(false, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime, jTxt_vcsValorUnitario,jFmt_vcsModeloAno, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar );
        util.limparCampos(jFmt_vcsModeloAno, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime, jTxt_vcsValorUnitario);
        
       
    }//GEN-LAST:event_jBtn_vcsConfirmarActionPerformed

    private void jBtn_vcsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsCancelarActionPerformed
       util.habilitar(false, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime, jTxt_vcsValorUnitario,jFmt_vcsModeloAno, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar );
        util.perguntar("Deseja Cancelar mesmo mermão?");
    }//GEN-LAST:event_jBtn_vcsCancelarActionPerformed

    private void jBtn_vcsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsPesquisarActionPerformed
        JDlgPesquisaProduto jDlgPesquisaProduto = new JDlgPesquisaProduto(null, true); 
       
        jDlgPesquisaProduto .setVisible(true);
    }//GEN-LAST:event_jBtn_vcsPesquisarActionPerformed

    private void jBtn_vcsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsIncluirActionPerformed
        util.habilitar(true, jTxt_vcsCodigo, jTxt_vcsCor, jTxt_vcsNome, jTxt_vcsNumero, jTxt_vcsTamanho, jTxt_vcsTime, jTxt_vcsValorUnitario,jFmt_vcsModeloAno, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(false, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar );
       
    }//GEN-LAST:event_jBtn_vcsIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProduto dialog = new JDlgProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_vcsAlterar;
    private javax.swing.JButton jBtn_vcsCancelar;
    private javax.swing.JButton jBtn_vcsConfirmar;
    private javax.swing.JButton jBtn_vcsExcluir;
    private javax.swing.JButton jBtn_vcsIncluir;
    private javax.swing.JButton jBtn_vcsPesquisar;
    private javax.swing.JFormattedTextField jFmt_vcsModeloAno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxt_vcsCodigo;
    private javax.swing.JTextField jTxt_vcsCor;
    private javax.swing.JTextField jTxt_vcsNome;
    private javax.swing.JTextField jTxt_vcsNumero;
    private javax.swing.JTextField jTxt_vcsTamanho;
    private javax.swing.JTextField jTxt_vcsTime;
    private javax.swing.JTextField jTxt_vcsValorUnitario;
    // End of variables declaration//GEN-END:variables

}
