/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import telasPesquisas.JDlgPesquisaCliente;
import tools.util;

/**
 *
 * @author vivic
 */
public class JDlgCliente extends javax.swing.JDialog {
 
     MaskFormatter mascaraCep, mascaraCpf, mascaraDataNascimento, mascaraNumeroFone, mascaraRg;
    /**
     * Creates new form JDlgCliente
     */
    public JDlgCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cliente");
        util.habilitar(false, jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone,
                jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade,
                jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia, jTxt_vcsPais, jTxt_vcsSexo,jFmt_vcsRg, jTxt_vcsUf, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsIncluir5 );
        
        
        try {
            mascaraCep = new MaskFormatter("#####-###");
            mascaraCpf = new MaskFormatter("###.###.###-##");
            mascaraDataNascimento = new MaskFormatter("##/##/####");
            mascaraNumeroFone = new MaskFormatter("(##)#####-####");
            mascaraRg = new MaskFormatter("#.###.###");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmt_vcsCep.setFormatterFactory(new DefaultFormatterFactory(mascaraCep));
        jFmt_vcsCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCpf));
        jFmt_vcsDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNascimento));
       jFmt_vcsNumeroFone.setFormatterFactory(new DefaultFormatterFactory(mascaraNumeroFone));
        jFmt_vcsRg.setFormatterFactory(new DefaultFormatterFactory(mascaraRg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTxt_vcsEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxt_vcsCodigo = new javax.swing.JTextField();
        jTxt_vcsCargo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jFmt_vcsCep = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTxt_vcsNomeCompleto = new javax.swing.JTextField();
        jTxt_vcsLogradouro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxt_vcsNomeFantasia = new javax.swing.JTextField();
        jTxt_vcsPais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxt_vcsSexo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxt_vcsUf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxt_vcsCidade = new javax.swing.JTextField();
        jFmt_vcsNumeroFone = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jFmt_vcsDataNascimento = new javax.swing.JFormattedTextField();
        jTxt_vcsBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxt_vcsNacionalidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmt_vcsRg = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFmt_vcsCpf = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jBtn_vcsConfirmar = new javax.swing.JButton();
        jBtn_vcsCancelar = new javax.swing.JButton();
        jBtn_vcsIncluir5 = new javax.swing.JButton();
        jBtn_vcsIncluir = new javax.swing.JButton();
        jBtn_vcsExcluir = new javax.swing.JButton();
        jBtn_vcsAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("Email");

        jLabel17.setText("Código");

        jLabel10.setText("Cargo");

        jLabel11.setText("CEP");

        jLabel2.setText("Nome Completo");

        jLabel12.setText("Logradouro");

        jLabel1.setText("Nome Fantasia");

        jLabel13.setText("País");

        jLabel3.setText("Sexo");

        jLabel14.setText("UF");

        jLabel4.setText("Data de Nascimento");

        jLabel15.setText("Cidade");

        jLabel5.setText("Numero de Telefone");

        jLabel16.setText("Bairro");

        jLabel6.setText("Nacionalidade");

        jLabel7.setText("RG");

        jLabel8.setText("CPF");

        jBtn_vcsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confimarIcon.png"))); // NOI18N
        jBtn_vcsConfirmar.setText("Confirmar");
        jBtn_vcsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsConfirmarActionPerformed(evt);
            }
        });

        jBtn_vcsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluirIcon.png"))); // NOI18N
        jBtn_vcsCancelar.setText("Cancelar");
        jBtn_vcsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsCancelarActionPerformed(evt);
            }
        });

        jBtn_vcsIncluir5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisarIcon.png"))); // NOI18N
        jBtn_vcsIncluir5.setText("Pesquisar");
        jBtn_vcsIncluir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsIncluir5ActionPerformed(evt);
            }
        });

        jBtn_vcsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluirIcon.png"))); // NOI18N
        jBtn_vcsIncluir.setText("Incluir");
        jBtn_vcsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsIncluirActionPerformed(evt);
            }
        });

        jBtn_vcsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Captura de tela 2024-03-26 233440.png"))); // NOI18N
        jBtn_vcsExcluir.setText("Excluir");
        jBtn_vcsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsExcluirActionPerformed(evt);
            }
        });

        jBtn_vcsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterarIcon.png"))); // NOI18N
        jBtn_vcsAlterar.setText("Alterar");
        jBtn_vcsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxt_vcsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFmt_vcsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFmt_vcsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxt_vcsUf, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jTxt_vcsCidade)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel4)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(381, 381, 381)
                                                .addComponent(jLabel10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxt_vcsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTxt_vcsCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFmt_vcsCep, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxt_vcsLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTxt_vcsPais, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(272, 272, 272)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jFmt_vcsRg, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(215, 215, 215)
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTxt_vcsNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTxt_vcsNomeFantasia))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTxt_vcsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jTxt_vcsNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFmt_vcsNumeroFone, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBtn_vcsIncluir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn_vcsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn_vcsExcluir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn_vcsConfirmar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn_vcsCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn_vcsIncluir5))))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxt_vcsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_vcsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_vcsNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmt_vcsNumeroFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxt_vcsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_vcsNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxt_vcsSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmt_vcsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmt_vcsCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxt_vcsUf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxt_vcsCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_vcsBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_vcsCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmt_vcsCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel7))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_vcsLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_vcsPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmt_vcsRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_vcsIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_vcsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_vcsExcluir)
                    .addComponent(jBtn_vcsConfirmar)
                    .addComponent(jBtn_vcsCancelar)
                    .addComponent(jBtn_vcsIncluir5))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_vcsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsConfirmarActionPerformed
         util.habilitar(false, jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone, jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade, jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia, jTxt_vcsPais,jFmt_vcsRg, jTxt_vcsSexo, jTxt_vcsUf, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsIncluir5 );
        util.limparCampos(jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone, jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade, jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia, jTxt_vcsPais, jTxt_vcsSexo, jTxt_vcsUf);
    }//GEN-LAST:event_jBtn_vcsConfirmarActionPerformed

    private void jBtn_vcsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsCancelarActionPerformed
           util.habilitar(false, jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone, jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade, jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia, jFmt_vcsRg,jTxt_vcsPais, jTxt_vcsSexo, jTxt_vcsUf, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsIncluir5 );
        util.perguntar("Deseja cancelar o registro brother?");
    }//GEN-LAST:event_jBtn_vcsCancelarActionPerformed

    private void jBtn_vcsIncluir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsIncluir5ActionPerformed
        JDlgPesquisaCliente jDlgPesquisaCliente = new JDlgPesquisaCliente(null, true); 
       
        jDlgPesquisaCliente.setVisible(true);
    }//GEN-LAST:event_jBtn_vcsIncluir5ActionPerformed

    private void jBtn_vcsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsIncluirActionPerformed
        util.habilitar(true, jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone, jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade, jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia,jFmt_vcsRg, jTxt_vcsPais, jTxt_vcsSexo, jTxt_vcsUf, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(false, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsIncluir5 );

    }//GEN-LAST:event_jBtn_vcsIncluirActionPerformed

    private void jBtn_vcsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsExcluirActionPerformed
                util.limparCampos(jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone, jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade, jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia,jFmt_vcsRg, jTxt_vcsPais, jTxt_vcsSexo, jTxt_vcsUf);
                util.mensagem("Registro excluido com sucesso!!!");
    }//GEN-LAST:event_jBtn_vcsExcluirActionPerformed

    private void jBtn_vcsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsAlterarActionPerformed
        util.habilitar(true, jTxt_vcsCodigo, jFmt_vcsCep, jFmt_vcsCpf, jFmt_vcsDataNascimento, jFmt_vcsNumeroFone, jTxt_vcsBairro,jTxt_vcsCargo, jTxt_vcsCargo, jTxt_vcsCidade, jTxt_vcsEmail, jTxt_vcsLogradouro, jTxt_vcsNacionalidade, jTxt_vcsNomeCompleto, jTxt_vcsNomeFantasia, jTxt_vcsPais,jFmt_vcsRg, jTxt_vcsSexo, jTxt_vcsUf, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(false, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsIncluir5 );

    }//GEN-LAST:event_jBtn_vcsAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgCliente dialog = new JDlgCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_vcsAlterar;
    private javax.swing.JButton jBtn_vcsCancelar;
    private javax.swing.JButton jBtn_vcsConfirmar;
    private javax.swing.JButton jBtn_vcsExcluir;
    private javax.swing.JButton jBtn_vcsIncluir;
    private javax.swing.JButton jBtn_vcsIncluir5;
    private javax.swing.JFormattedTextField jFmt_vcsCep;
    private javax.swing.JFormattedTextField jFmt_vcsCpf;
    private javax.swing.JFormattedTextField jFmt_vcsDataNascimento;
    private javax.swing.JFormattedTextField jFmt_vcsNumeroFone;
    private javax.swing.JFormattedTextField jFmt_vcsRg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxt_vcsBairro;
    private javax.swing.JTextField jTxt_vcsCargo;
    private javax.swing.JTextField jTxt_vcsCidade;
    private javax.swing.JTextField jTxt_vcsCodigo;
    private javax.swing.JTextField jTxt_vcsEmail;
    private javax.swing.JTextField jTxt_vcsLogradouro;
    private javax.swing.JTextField jTxt_vcsNacionalidade;
    private javax.swing.JTextField jTxt_vcsNomeCompleto;
    private javax.swing.JTextField jTxt_vcsNomeFantasia;
    private javax.swing.JTextField jTxt_vcsPais;
    private javax.swing.JTextField jTxt_vcsSexo;
    private javax.swing.JTextField jTxt_vcsUf;
    // End of variables declaration//GEN-END:variables
}
