/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import telasPesquisas.JDlgPesquisaUsuarios;
import tools.util;

/**
 *
 * @author vivic
 */
public class JDlgUsuarios extends javax.swing.JDialog {

    
     MaskFormatter mascaraCPF, mascaraDataNascimento;
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        setTitle("Usuarios");
        
        
       
        util.habilitar(false, jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
        jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo, jBtn_vcsCancelar, jBtn_vcsConfirmar);
        util.habilitar(true, jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar); 
        
         try {
            
             mascaraCPF = new MaskFormatter("###.###.###-##");
             mascaraDataNascimento = new MaskFormatter("##/##/####");
             
             
        } catch  (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
         
       jFmt_vcsCPF.setFormatterFactory( new DefaultFormatterFactory( mascaraCPF )); 
       jFmt_vcsDataNascimento.setFormatterFactory( new DefaultFormatterFactory(mascaraDataNascimento) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxt_vcsCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxt_vcsNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxt_vcsApelido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFmt_vcsDataNascimento = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jPwf_vcsSenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jCbo_vcsNivel = new javax.swing.JComboBox<>();
        jChb_vcsAtivo = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jBtn_vcsIncluir = new javax.swing.JButton();
        jBtn_vcsExcluir = new javax.swing.JButton();
        jBtn_vcsAlterar = new javax.swing.JButton();
        jBtn_vcsConfirmar = new javax.swing.JButton();
        jBtn_vcsCancelar = new javax.swing.JButton();
        jBtn_vcsPesquisar = new javax.swing.JButton();
        jFmt_vcsCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jTxt_vcsNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_vcsNomeActionPerformed(evt);
            }
        });

        jLabel4.setText("Apelido");

        jLabel5.setText("CPF");

        jLabel6.setText("Data de Nascimento");

        jFmt_vcsDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmt_vcsDataNascimentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Senha");

        jPwf_vcsSenha.setText("jPasswordField1");

        jLabel8.setText("Nivel");

        jCbo_vcsNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "ANONIMO", "CLIENTE" }));
        jCbo_vcsNivel.setSelectedIndex(-1);

        jChb_vcsAtivo.setText("Ativo");

        jBtn_vcsIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluirIcon.png"))); // NOI18N
        jBtn_vcsIncluir.setText("Incluir");
        jBtn_vcsIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsIncluirActionPerformed(evt);
            }
        });

        jBtn_vcsExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Captura de tela 2024-03-26 233440.png"))); // NOI18N
        jBtn_vcsExcluir.setText("Excluir");
        jBtn_vcsExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsExcluirActionPerformed(evt);
            }
        });

        jBtn_vcsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterarIcon.png"))); // NOI18N
        jBtn_vcsAlterar.setText("Alterar");
        jBtn_vcsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsAlterarActionPerformed(evt);
            }
        });

        jBtn_vcsConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confimarIcon.png"))); // NOI18N
        jBtn_vcsConfirmar.setText("Confirmar");
        jBtn_vcsConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsConfirmarActionPerformed(evt);
            }
        });

        jBtn_vcsCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluirIcon.png"))); // NOI18N
        jBtn_vcsCancelar.setText("Cancelar");
        jBtn_vcsCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsCancelarActionPerformed(evt);
            }
        });

        jBtn_vcsPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisarIcon.png"))); // NOI18N
        jBtn_vcsPesquisar.setText("Pesquisar");
        jBtn_vcsPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_vcsPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jPwf_vcsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChb_vcsAtivo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxt_vcsCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTxt_vcsNome, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jTxt_vcsApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFmt_vcsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jFmt_vcsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCbo_vcsNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtn_vcsIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_vcsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_vcsExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_vcsConfirmar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_vcsCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_vcsPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(404, 404, 404))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxt_vcsCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxt_vcsNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxt_vcsApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmt_vcsDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmt_vcsCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jPwf_vcsSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChb_vcsAtivo)
                            .addComponent(jCbo_vcsNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_vcsIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_vcsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_vcsExcluir)
                    .addComponent(jBtn_vcsConfirmar)
                    .addComponent(jBtn_vcsCancelar)
                    .addComponent(jBtn_vcsPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmt_vcsDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmt_vcsDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmt_vcsDataNascimentoActionPerformed

    private void jBtn_vcsIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsIncluirActionPerformed
         util.habilitar(true, jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
       jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo, jBtn_vcsCancelar, jBtn_vcsConfirmar);
         util.habilitar(false,jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar);
       
    }//GEN-LAST:event_jBtn_vcsIncluirActionPerformed

    private void jBtn_vcsExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsExcluirActionPerformed
        util.limparCampos(jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
       jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo);
        util.mensagem("Registro excluido bebê!");
    }//GEN-LAST:event_jBtn_vcsExcluirActionPerformed

    private void jBtn_vcsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsAlterarActionPerformed
       util.habilitar(true, jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
       jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo, jBtn_vcsCancelar, jBtn_vcsConfirmar);
         util.habilitar(false,jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar);
    }//GEN-LAST:event_jBtn_vcsAlterarActionPerformed

    private void jBtn_vcsConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsConfirmarActionPerformed
        util.habilitar(false, jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
       jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo, jBtn_vcsCancelar, jBtn_vcsConfirmar);
         util.habilitar(true,jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar);
          util.limparCampos(jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
       jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo);
    }//GEN-LAST:event_jBtn_vcsConfirmarActionPerformed

    private void jBtn_vcsCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsCancelarActionPerformed
         util.habilitar(false, jTxt_vcsCodigo, jTxt_vcsNome, jTxt_vcsApelido, jFmt_vcsCPF, jFmt_vcsDataNascimento,
       jPwf_vcsSenha,  jCbo_vcsNivel, jChb_vcsAtivo, jBtn_vcsCancelar, jBtn_vcsConfirmar);
         util.habilitar(true,jBtn_vcsIncluir, jBtn_vcsAlterar, jBtn_vcsExcluir, jBtn_vcsPesquisar);
         util.perguntar("Deseja cancelar o registro mesmo?");
    }//GEN-LAST:event_jBtn_vcsCancelarActionPerformed

    private void jBtn_vcsPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_vcsPesquisarActionPerformed
       JDlgPesquisaUsuarios jDlgPesquisaUsuarios = new JDlgPesquisaUsuarios(null, true); 
       
        jDlgPesquisaUsuarios.setVisible(true);
    }//GEN-LAST:event_jBtn_vcsPesquisarActionPerformed

    private void jTxt_vcsNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_vcsNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_vcsNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_vcsAlterar;
    private javax.swing.JButton jBtn_vcsCancelar;
    private javax.swing.JButton jBtn_vcsConfirmar;
    private javax.swing.JButton jBtn_vcsExcluir;
    private javax.swing.JButton jBtn_vcsIncluir;
    private javax.swing.JButton jBtn_vcsPesquisar;
    private javax.swing.JComboBox<String> jCbo_vcsNivel;
    private javax.swing.JCheckBox jChb_vcsAtivo;
    private javax.swing.JFormattedTextField jFmt_vcsCPF;
    private javax.swing.JFormattedTextField jFmt_vcsDataNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPwf_vcsSenha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxt_vcsApelido;
    private javax.swing.JTextField jTxt_vcsCodigo;
    private javax.swing.JTextField jTxt_vcsNome;
    // End of variables declaration//GEN-END:variables
}
