package bean;
// Generated 30/07/2024 08:00:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcsCliente generated by hbm2java
 */
@Entity
@Table(name="vcs_cliente"
    ,catalog="lojaroupas"
)
public class VcsCliente  implements java.io.Serializable {


     private int idvcsCliente;
     private String vcsNomeFantasia;
     private String vcsNomeCompleto;
     private String vcsSexo;
     private Date vcsDataNascimento;
     private String vcsNumeroFone;
     private String vcsNacionalidade;
     private String vcsRg;
     private String vcsCpf;
     private String vcsEmail;
     private String vcsCargo;
     private String vcsCep;
     private String vcsLogradouro;
     private String vcsEstadosUf;
     private Set vcsVendas = new HashSet(0);

    public VcsCliente() {
    }

	
    public VcsCliente(int idvcsCliente, String vcsNomeFantasia, String vcsNomeCompleto, String vcsSexo, String vcsNumeroFone, String vcsRg, String vcsCpf, String vcsEmail, String vcsCargo, String vcsCep, String vcsLogradouro, String vcsEstadosUf) {
        this.idvcsCliente = idvcsCliente;
        this.vcsNomeFantasia = vcsNomeFantasia;
        this.vcsNomeCompleto = vcsNomeCompleto;
        this.vcsSexo = vcsSexo;
        this.vcsNumeroFone = vcsNumeroFone;
        this.vcsRg = vcsRg;
        this.vcsCpf = vcsCpf;
        this.vcsEmail = vcsEmail;
        this.vcsCargo = vcsCargo;
        this.vcsCep = vcsCep;
        this.vcsLogradouro = vcsLogradouro;
        this.vcsEstadosUf = vcsEstadosUf;
    }
    public VcsCliente(int idvcsCliente, String vcsNomeFantasia, String vcsNomeCompleto, String vcsSexo, Date vcsDataNascimento, String vcsNumeroFone, String vcsNacionalidade, String vcsRg, String vcsCpf, String vcsEmail, String vcsCargo, String vcsCep, String vcsLogradouro, String vcsEstadosUf, Set vcsVendas) {
       this.idvcsCliente = idvcsCliente;
       this.vcsNomeFantasia = vcsNomeFantasia;
       this.vcsNomeCompleto = vcsNomeCompleto;
       this.vcsSexo = vcsSexo;
       this.vcsDataNascimento = vcsDataNascimento;
       this.vcsNumeroFone = vcsNumeroFone;
       this.vcsNacionalidade = vcsNacionalidade;
       this.vcsRg = vcsRg;
       this.vcsCpf = vcsCpf;
       this.vcsEmail = vcsEmail;
       this.vcsCargo = vcsCargo;
       this.vcsCep = vcsCep;
       this.vcsLogradouro = vcsLogradouro;
       this.vcsEstadosUf = vcsEstadosUf;
       this.vcsVendas = vcsVendas;
    }
   
     @Id 

    
    @Column(name="idvcs_cliente", unique=true, nullable=false)
    public int getIdvcsCliente() {
        return this.idvcsCliente;
    }
    
    public void setIdvcsCliente(int idvcsCliente) {
        this.idvcsCliente = idvcsCliente;
    }

    
    @Column(name="vcs_nomeFantasia", nullable=false, length=45)
    public String getVcsNomeFantasia() {
        return this.vcsNomeFantasia;
    }
    
    public void setVcsNomeFantasia(String vcsNomeFantasia) {
        this.vcsNomeFantasia = vcsNomeFantasia;
    }

    
    @Column(name="vcs_nomeCompleto", nullable=false, length=45)
    public String getVcsNomeCompleto() {
        return this.vcsNomeCompleto;
    }
    
    public void setVcsNomeCompleto(String vcsNomeCompleto) {
        this.vcsNomeCompleto = vcsNomeCompleto;
    }

    
    @Column(name="vcs_sexo", nullable=false, length=45)
    public String getVcsSexo() {
        return this.vcsSexo;
    }
    
    public void setVcsSexo(String vcsSexo) {
        this.vcsSexo = vcsSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcs_dataNascimento", length=10)
    public Date getVcsDataNascimento() {
        return this.vcsDataNascimento;
    }
    
    public void setVcsDataNascimento(Date vcsDataNascimento) {
        this.vcsDataNascimento = vcsDataNascimento;
    }

    
    @Column(name="vcs_numeroFone", nullable=false, length=11)
    public String getVcsNumeroFone() {
        return this.vcsNumeroFone;
    }
    
    public void setVcsNumeroFone(String vcsNumeroFone) {
        this.vcsNumeroFone = vcsNumeroFone;
    }

    
    @Column(name="vcs_Nacionalidade", length=60)
    public String getVcsNacionalidade() {
        return this.vcsNacionalidade;
    }
    
    public void setVcsNacionalidade(String vcsNacionalidade) {
        this.vcsNacionalidade = vcsNacionalidade;
    }

    
    @Column(name="vcs_rg", nullable=false, length=45)
    public String getVcsRg() {
        return this.vcsRg;
    }
    
    public void setVcsRg(String vcsRg) {
        this.vcsRg = vcsRg;
    }

    
    @Column(name="vcs_cpf", nullable=false, length=45)
    public String getVcsCpf() {
        return this.vcsCpf;
    }
    
    public void setVcsCpf(String vcsCpf) {
        this.vcsCpf = vcsCpf;
    }

    
    @Column(name="vcs_email", nullable=false, length=45)
    public String getVcsEmail() {
        return this.vcsEmail;
    }
    
    public void setVcsEmail(String vcsEmail) {
        this.vcsEmail = vcsEmail;
    }

    
    @Column(name="vcs_cargo", nullable=false, length=45)
    public String getVcsCargo() {
        return this.vcsCargo;
    }
    
    public void setVcsCargo(String vcsCargo) {
        this.vcsCargo = vcsCargo;
    }

    
    @Column(name="vcs_cep", nullable=false, length=45)
    public String getVcsCep() {
        return this.vcsCep;
    }
    
    public void setVcsCep(String vcsCep) {
        this.vcsCep = vcsCep;
    }

    
    @Column(name="vcs_logradouro", nullable=false, length=45)
    public String getVcsLogradouro() {
        return this.vcsLogradouro;
    }
    
    public void setVcsLogradouro(String vcsLogradouro) {
        this.vcsLogradouro = vcsLogradouro;
    }

    
    @Column(name="vcs_estadosUf", nullable=false, length=45)
    public String getVcsEstadosUf() {
        return this.vcsEstadosUf;
    }
    
    public void setVcsEstadosUf(String vcsEstadosUf) {
        this.vcsEstadosUf = vcsEstadosUf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vcsCliente")
    public Set getVcsVendas() {
        return this.vcsVendas;
    }
    
    public void setVcsVendas(Set vcsVendas) {
        this.vcsVendas = vcsVendas;
    }




}


