package bean;
// Generated 30/07/2024 08:00:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcsProduto generated by hbm2java
 */
@Entity
@Table(name="vcs_produto"
    ,catalog="lojaroupas"
)
public class VcsProduto  implements java.io.Serializable {


     private int vcsIdProduto;
     private String vcsTime;
     private String vcsCor;
     private String vcsTamanho;
     private Date vcsModeloAno;
     private String vcsNumero;
     private String vcsNome;
     private BigDecimal vcsValorUnitario;
     private Set vcsVendaprodutos = new HashSet(0);

    public VcsProduto() {
    }

	
    public VcsProduto(int vcsIdProduto, String vcsTime, String vcsCor, String vcsTamanho, String vcsNumero, String vcsNome, BigDecimal vcsValorUnitario) {
        this.vcsIdProduto = vcsIdProduto;
        this.vcsTime = vcsTime;
        this.vcsCor = vcsCor;
        this.vcsTamanho = vcsTamanho;
        this.vcsNumero = vcsNumero;
        this.vcsNome = vcsNome;
        this.vcsValorUnitario = vcsValorUnitario;
    }
    public VcsProduto(int vcsIdProduto, String vcsTime, String vcsCor, String vcsTamanho, Date vcsModeloAno, String vcsNumero, String vcsNome, BigDecimal vcsValorUnitario, Set vcsVendaprodutos) {
       this.vcsIdProduto = vcsIdProduto;
       this.vcsTime = vcsTime;
       this.vcsCor = vcsCor;
       this.vcsTamanho = vcsTamanho;
       this.vcsModeloAno = vcsModeloAno;
       this.vcsNumero = vcsNumero;
       this.vcsNome = vcsNome;
       this.vcsValorUnitario = vcsValorUnitario;
       this.vcsVendaprodutos = vcsVendaprodutos;
    }
   
     @Id 

    
    @Column(name="vcs_idProduto", unique=true, nullable=false)
    public int getVcsIdProduto() {
        return this.vcsIdProduto;
    }
    
    public void setVcsIdProduto(int vcsIdProduto) {
        this.vcsIdProduto = vcsIdProduto;
    }

    
    @Column(name="vcs_time", nullable=false, length=30)
    public String getVcsTime() {
        return this.vcsTime;
    }
    
    public void setVcsTime(String vcsTime) {
        this.vcsTime = vcsTime;
    }

    
    @Column(name="vcs_cor", nullable=false, length=25)
    public String getVcsCor() {
        return this.vcsCor;
    }
    
    public void setVcsCor(String vcsCor) {
        this.vcsCor = vcsCor;
    }

    
    @Column(name="vcs_tamanho", nullable=false, length=45)
    public String getVcsTamanho() {
        return this.vcsTamanho;
    }
    
    public void setVcsTamanho(String vcsTamanho) {
        this.vcsTamanho = vcsTamanho;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcs_modeloAno", length=10)
    public Date getVcsModeloAno() {
        return this.vcsModeloAno;
    }
    
    public void setVcsModeloAno(Date vcsModeloAno) {
        this.vcsModeloAno = vcsModeloAno;
    }

    
    @Column(name="vcs_numero", nullable=false, length=45)
    public String getVcsNumero() {
        return this.vcsNumero;
    }
    
    public void setVcsNumero(String vcsNumero) {
        this.vcsNumero = vcsNumero;
    }

    
    @Column(name="vcs_nome", nullable=false, length=3)
    public String getVcsNome() {
        return this.vcsNome;
    }
    
    public void setVcsNome(String vcsNome) {
        this.vcsNome = vcsNome;
    }

    
    @Column(name="vcs_valorUnitario", nullable=false, precision=10)
    public BigDecimal getVcsValorUnitario() {
        return this.vcsValorUnitario;
    }
    
    public void setVcsValorUnitario(BigDecimal vcsValorUnitario) {
        this.vcsValorUnitario = vcsValorUnitario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vcsProduto")
    public Set getVcsVendaprodutos() {
        return this.vcsVendaprodutos;
    }
    
    public void setVcsVendaprodutos(Set vcsVendaprodutos) {
        this.vcsVendaprodutos = vcsVendaprodutos;
    }




}


