package bean;
// Generated 30/07/2024 08:00:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcsUsuarios generated by hbm2java
 */
@Entity
@Table(name="vcs_usuarios"
    ,catalog="lojaroupas"
)
public class VcsUsuarios  implements java.io.Serializable {


     private int vcsIdusuarios;
     private String vcsNome;
     private String vcsApelido;
     private String vcsCpf;
     private Date vcsDataNascimento;
     private String vcsSenha;
     private int vcsNivel;
     private String vcsAtivo;

    public VcsUsuarios() {
    }

    public VcsUsuarios(int vcsIdusuarios, String vcsNome, String vcsApelido, String vcsCpf, Date vcsDataNascimento, String vcsSenha, int vcsNivel, String vcsAtivo) {
       this.vcsIdusuarios = vcsIdusuarios;
       this.vcsNome = vcsNome;
       this.vcsApelido = vcsApelido;
       this.vcsCpf = vcsCpf;
       this.vcsDataNascimento = vcsDataNascimento;
       this.vcsSenha = vcsSenha;
       this.vcsNivel = vcsNivel;
       this.vcsAtivo = vcsAtivo;
    }
   
     @Id 

    
    @Column(name="vcs_idusuarios", unique=true, nullable=false)
    public int getVcsIdusuarios() {
        return this.vcsIdusuarios;
    }
    
    public void setVcsIdusuarios(int vcsIdusuarios) {
        this.vcsIdusuarios = vcsIdusuarios;
    }

    
    @Column(name="vcs_nome", nullable=false, length=50)
    public String getVcsNome() {
        return this.vcsNome;
    }
    
    public void setVcsNome(String vcsNome) {
        this.vcsNome = vcsNome;
    }

    
    @Column(name="vcs_apelido", nullable=false, length=25)
    public String getVcsApelido() {
        return this.vcsApelido;
    }
    
    public void setVcsApelido(String vcsApelido) {
        this.vcsApelido = vcsApelido;
    }

    
    @Column(name="vcs_cpf", nullable=false, length=4)
    public String getVcsCpf() {
        return this.vcsCpf;
    }
    
    public void setVcsCpf(String vcsCpf) {
        this.vcsCpf = vcsCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcs_dataNascimento", nullable=false, length=10)
    public Date getVcsDataNascimento() {
        return this.vcsDataNascimento;
    }
    
    public void setVcsDataNascimento(Date vcsDataNascimento) {
        this.vcsDataNascimento = vcsDataNascimento;
    }

    
    @Column(name="vcs_senha", nullable=false, length=20)
    public String getVcsSenha() {
        return this.vcsSenha;
    }
    
    public void setVcsSenha(String vcsSenha) {
        this.vcsSenha = vcsSenha;
    }

    
    @Column(name="vcs_nivel", nullable=false)
    public int getVcsNivel() {
        return this.vcsNivel;
    }
    
    public void setVcsNivel(int vcsNivel) {
        this.vcsNivel = vcsNivel;
    }

    
    @Column(name="vcs_ativo", nullable=false, length=1)
    public String getVcsAtivo() {
        return this.vcsAtivo;
    }
    
    public void setVcsAtivo(String vcsAtivo) {
        this.vcsAtivo = vcsAtivo;
    }




}


