package bean;
// Generated 30/07/2024 08:00:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VcsVendedor generated by hbm2java
 */
@Entity
@Table(name="vcs_vendedor"
    ,catalog="lojaroupas"
)
public class VcsVendedor  implements java.io.Serializable {


     private int vcsIdvendedor;
     private String vcsNome;
     private String vcsSenha;
     private String vcsNivel;
     private String vcsAtivo;
     private Set vcsVendas = new HashSet(0);

    public VcsVendedor() {
    }

	
    public VcsVendedor(int vcsIdvendedor, String vcsNome, String vcsSenha, String vcsNivel, String vcsAtivo) {
        this.vcsIdvendedor = vcsIdvendedor;
        this.vcsNome = vcsNome;
        this.vcsSenha = vcsSenha;
        this.vcsNivel = vcsNivel;
        this.vcsAtivo = vcsAtivo;
    }
    public VcsVendedor(int vcsIdvendedor, String vcsNome, String vcsSenha, String vcsNivel, String vcsAtivo, Set vcsVendas) {
       this.vcsIdvendedor = vcsIdvendedor;
       this.vcsNome = vcsNome;
       this.vcsSenha = vcsSenha;
       this.vcsNivel = vcsNivel;
       this.vcsAtivo = vcsAtivo;
       this.vcsVendas = vcsVendas;
    }
   
     @Id 

    
    @Column(name="vcs_idvendedor", unique=true, nullable=false)
    public int getVcsIdvendedor() {
        return this.vcsIdvendedor;
    }
    
    public void setVcsIdvendedor(int vcsIdvendedor) {
        this.vcsIdvendedor = vcsIdvendedor;
    }

    
    @Column(name="vcs_nome", nullable=false, length=45)
    public String getVcsNome() {
        return this.vcsNome;
    }
    
    public void setVcsNome(String vcsNome) {
        this.vcsNome = vcsNome;
    }

    
    @Column(name="vcs_senha", nullable=false, length=8)
    public String getVcsSenha() {
        return this.vcsSenha;
    }
    
    public void setVcsSenha(String vcsSenha) {
        this.vcsSenha = vcsSenha;
    }

    
    @Column(name="vcs_Nivel", nullable=false, length=45)
    public String getVcsNivel() {
        return this.vcsNivel;
    }
    
    public void setVcsNivel(String vcsNivel) {
        this.vcsNivel = vcsNivel;
    }

    
    @Column(name="vcs_ativo", nullable=false, length=60)
    public String getVcsAtivo() {
        return this.vcsAtivo;
    }
    
    public void setVcsAtivo(String vcsAtivo) {
        this.vcsAtivo = vcsAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vcsVendedor")
    public Set getVcsVendas() {
        return this.vcsVendas;
    }
    
    public void setVcsVendas(Set vcsVendas) {
        this.vcsVendas = vcsVendas;
    }




}


