package bean;
// Generated 30/07/2024 08:00:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VcsVendaproduto generated by hbm2java
 */
@Entity
@Table(name="vcs_vendaproduto"
    ,catalog="lojaroupas"
)
public class VcsVendaproduto  implements java.io.Serializable {


     private int vcsIdvendaProduto;
     private VcsProduto vcsProduto;
     private VcsVenda vcsVenda;
     private Integer vcsQuantidade;
     private BigDecimal vcsValorUnitario;
     private BigDecimal vcsTotal;

    public VcsVendaproduto() {
    }

	
    public VcsVendaproduto(int vcsIdvendaProduto, VcsProduto vcsProduto, VcsVenda vcsVenda) {
        this.vcsIdvendaProduto = vcsIdvendaProduto;
        this.vcsProduto = vcsProduto;
        this.vcsVenda = vcsVenda;
    }
    public VcsVendaproduto(int vcsIdvendaProduto, VcsProduto vcsProduto, VcsVenda vcsVenda, Integer vcsQuantidade, BigDecimal vcsValorUnitario, BigDecimal vcsTotal) {
       this.vcsIdvendaProduto = vcsIdvendaProduto;
       this.vcsProduto = vcsProduto;
       this.vcsVenda = vcsVenda;
       this.vcsQuantidade = vcsQuantidade;
       this.vcsValorUnitario = vcsValorUnitario;
       this.vcsTotal = vcsTotal;
    }
   
     @Id 

    
    @Column(name="vcs_idvendaProduto", unique=true, nullable=false)
    public int getVcsIdvendaProduto() {
        return this.vcsIdvendaProduto;
    }
    
    public void setVcsIdvendaProduto(int vcsIdvendaProduto) {
        this.vcsIdvendaProduto = vcsIdvendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vcs_fkproduto", nullable=false)
    public VcsProduto getVcsProduto() {
        return this.vcsProduto;
    }
    
    public void setVcsProduto(VcsProduto vcsProduto) {
        this.vcsProduto = vcsProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vcs_fkVenda", nullable=false)
    public VcsVenda getVcsVenda() {
        return this.vcsVenda;
    }
    
    public void setVcsVenda(VcsVenda vcsVenda) {
        this.vcsVenda = vcsVenda;
    }

    
    @Column(name="vcs_quantidade")
    public Integer getVcsQuantidade() {
        return this.vcsQuantidade;
    }
    
    public void setVcsQuantidade(Integer vcsQuantidade) {
        this.vcsQuantidade = vcsQuantidade;
    }

    
    @Column(name="vcs_valorUnitario", precision=10)
    public BigDecimal getVcsValorUnitario() {
        return this.vcsValorUnitario;
    }
    
    public void setVcsValorUnitario(BigDecimal vcsValorUnitario) {
        this.vcsValorUnitario = vcsValorUnitario;
    }

    
    @Column(name="vcs_total", precision=10)
    public BigDecimal getVcsTotal() {
        return this.vcsTotal;
    }
    
    public void setVcsTotal(BigDecimal vcsTotal) {
        this.vcsTotal = vcsTotal;
    }




}


