package bean;
// Generated 30/07/2024 08:00:47 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VcsVenda generated by hbm2java
 */
@Entity
@Table(name="vcs_venda"
    ,catalog="lojaroupas"
)
public class VcsVenda  implements java.io.Serializable {


     private int vcsIdvenda;
     private VcsCliente vcsCliente;
     private VcsVendedor vcsVendedor;
     private Date vcsData;
     private BigDecimal vcsTotal;
     private Set vcsVendaprodutos = new HashSet(0);

    public VcsVenda() {
    }

	
    public VcsVenda(int vcsIdvenda, VcsCliente vcsCliente, VcsVendedor vcsVendedor) {
        this.vcsIdvenda = vcsIdvenda;
        this.vcsCliente = vcsCliente;
        this.vcsVendedor = vcsVendedor;
    }
    public VcsVenda(int vcsIdvenda, VcsCliente vcsCliente, VcsVendedor vcsVendedor, Date vcsData, BigDecimal vcsTotal, Set vcsVendaprodutos) {
       this.vcsIdvenda = vcsIdvenda;
       this.vcsCliente = vcsCliente;
       this.vcsVendedor = vcsVendedor;
       this.vcsData = vcsData;
       this.vcsTotal = vcsTotal;
       this.vcsVendaprodutos = vcsVendaprodutos;
    }
   
     @Id 

    
    @Column(name="vcs_idvenda", unique=true, nullable=false)
    public int getVcsIdvenda() {
        return this.vcsIdvenda;
    }
    
    public void setVcsIdvenda(int vcsIdvenda) {
        this.vcsIdvenda = vcsIdvenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vcs_fkCliente", nullable=false)
    public VcsCliente getVcsCliente() {
        return this.vcsCliente;
    }
    
    public void setVcsCliente(VcsCliente vcsCliente) {
        this.vcsCliente = vcsCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vcs_fkvendedor", nullable=false)
    public VcsVendedor getVcsVendedor() {
        return this.vcsVendedor;
    }
    
    public void setVcsVendedor(VcsVendedor vcsVendedor) {
        this.vcsVendedor = vcsVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="vcs_data", length=10)
    public Date getVcsData() {
        return this.vcsData;
    }
    
    public void setVcsData(Date vcsData) {
        this.vcsData = vcsData;
    }

    
    @Column(name="vcs_total", precision=10)
    public BigDecimal getVcsTotal() {
        return this.vcsTotal;
    }
    
    public void setVcsTotal(BigDecimal vcsTotal) {
        this.vcsTotal = vcsTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vcsVenda")
    public Set getVcsVendaprodutos() {
        return this.vcsVendaprodutos;
    }
    
    public void setVcsVendaprodutos(Set vcsVendaprodutos) {
        this.vcsVendaprodutos = vcsVendaprodutos;
    }




}


